eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

server:
  port: 8078

spring:
  application:
    name: turbine

turbine:
  app-config: MALL-PRODUCT, MALL-USER
  cluster-name-expression: new String("default")
