eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    prefer-ip-address: true

info:
  app:
    name: mall-product-a
  company:
    name: avence.club
  build:
    artifact-id: $project.artifactId$
    model-version: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8086

spring:
  application:
    name: mall-product
  security:
    user:
      name: admin
      password: admin
      roles:
        - User
