eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/html
        - application/xml
        - application/json
      min-request-size: 0
  hystrix:
    enabled: true

logging:
  level:
    club.avence.springcloud: debug

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8074/oauth/token
      client-id: productApp
      client-secret: aa3sd#gk
      grant-type: client_credentials

server:
  port: 8093

spring:
  application:
    name: mall-web-feign
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin
      roles:
        - User
