eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true

info:
  app:
    name: mall-product-a
  company:
    name: avence.club
  build:
    artifact-id: $project.artifactId$
    model-version: $project.modelVersion$

server:
  port: 8085

spring:
  application:
    name: mall-product
  security:
    user:
      name: admin
      password: admin
      roles:
        - User