eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@eureka-b:8084/eureka
  instance:
    hostname: eureka-a
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false

server:
  port: 8083

spring:
  application:
    name: config-server-eureka
  security:
    user:
      name: admin
      password: admin
