eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@eureka-b:8082/eureka
  instance:
    hostname: eureka-a
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: true

server:
  port: 8080

spring:
  application:
    name: eureka
  security:
    user:
      name: admin
      password: admin
