debug: false

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

server:
  port: 8077
  servlet:
    context-path: /

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
          - Path='/' + serviceId + '/**'
          filters:
          - RewritePath='/' + serviceId + '/(?<remaining>.*)', "/${remaining}"
          - AddRequestHeader="Authorization", "Basic YWRtaW46YWRtaW4="
    sentinel:
      datasource:
        ds:
          nacos:
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow
            server-addr: localhost:8848
    transport:
      dashboard: http://localhost:8070
  rabbitmq:
    addresses: 172.17.0.2:5672
    username: admin
    password: admin
  security:
    user:
      name: admin
      password: admin
      roles:
        - User
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8071
    sender:
      type: RABBIT
