eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

server:
  port: 8077

spring:
  application:
    name: zuul
