eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

server:
  port: 8090

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8074/oauth/token
      client-id: productApp
      client-secret: aa3sd#gk
      grant-type: client_credentials

spring:
  application:
    name: mall-web-a
  rabbitmq:
    addresses: 172.17.0.2:5672
    username: admin
    password: admin
  security:
    user:
      name: admin
      password: admin
      roles:
        - User
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8071
    sender:
      type: rabbit
