eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@eureka-b:8080/eureka
  instance:
    hostname: eureka-b
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false

server:
  port: 8082

spring:
  application:
    name: eureka-b
  security:
    user:
      name: admin
      password: admin
