eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

server:
  port: 8076

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///F:/projects/config-repository
  security:
    user:
      name: admin
      password: admin
      roles:
        - User
