eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

server:
  port: 8091

spring:
  application:
    name: mall-web-b
  rabbitmq:
    addresses: 172.17.0.2:5672
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8071
    sender:
      type: rabbit
