eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

logging:
  level:
    club.avence.springcloud: debug

server:
  port: 8093

spring:
  application:
    name: oauth2-server
