eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-a:8080/eureka, http://admin:admin@eureka-b:8082/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8074

spring:
  application:
    name: oauth2-server
  security:
    user:
      name: admin
      password: admin
      roles:
        - User
