eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@eureka-a:8083/eureka
  instance:
    hostname: eureka-b
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  server:
    eviction-interval-timer-in-ms: 1000

server:
  port: 8084

spring:
  application:
    name: config-server-eureka
  security:
    user:
      name: admin
      password: admin
