eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@eureka-a:8083/eureka
  instance:
    hostname: eureka-b
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false

server:
  port: 8084

spring:
  application:
    name: config-server-eureka
  security:
    user:
      name: admin
      password: admin
